// ============================================
// Car Experience — Vehicle Database
// ============================================

export const CARS = [
  {
    id: 'ferrari_f8',
    name: 'Ferrari F8 Tributo',
    manufacturer: 'Ferrari',
    country: 'Italy',
    year: 2024,
    class: 'S',
    engine: '3.9L Twin-Turbo V8',
    horsepower: 710,
    torque: 770,
    weight: 1330,
    driveType: 'RWD',
    transmission: '7-Speed DCT',
    topSpeed: 340,
    acceleration: 2.9,
    handling: 9.2,
    braking: 9.0,
    turbo: true,
    stars: 5,
    color: { primary: '#DC143C', accent: '#1a1a1a', metalness: 0.9, roughness: 0.15 },
    bodyStyle: 'supercar',
    description: 'The pinnacle of Ferrari\'s mid-engine V8 dynasty. Twin-turbo fury with surgical precision.',
  },
  {
    id: 'lambo_huracan',
    name: 'Lamborghini Huracán EVO',
    manufacturer: 'Lamborghini',
    country: 'Italy',
    year: 2023,
    class: 'S',
    engine: '5.2L Naturally Aspirated V10',
    horsepower: 640,
    torque: 600,
    weight: 1382,
    driveType: 'AWD',
    transmission: '7-Speed DCT',
    topSpeed: 325,
    acceleration: 2.9,
    handling: 9.5,
    braking: 9.3,
    turbo: false,
    stars: 5,
    color: { primary: '#FFD700', accent: '#111111', metalness: 0.85, roughness: 0.1 },
    bodyStyle: 'supercar',
    description: 'A screaming V10 masterpiece. Naturally aspirated perfection with all-wheel grip.',
  },
  {
    id: 'porsche_911',
    name: 'Porsche 911 GT3 RS',
    manufacturer: 'Porsche',
    country: 'Germany',
    year: 2024,
    class: 'A',
    engine: '4.0L Naturally Aspirated Flat-6',
    horsepower: 525,
    torque: 465,
    weight: 1450,
    driveType: 'RWD',
    transmission: '7-Speed PDK',
    topSpeed: 296,
    acceleration: 3.2,
    handling: 9.8,
    braking: 9.6,
    turbo: false,
    stars: 5,
    color: { primary: '#FFFFFF', accent: '#2563eb', metalness: 0.7, roughness: 0.2 },
    bodyStyle: 'sports',
    description: 'Track-bred precision from Stuttgart. The benchmark for driver engagement.',
  },
  {
    id: 'mclaren_720s',
    name: 'McLaren 720S',
    manufacturer: 'McLaren',
    country: 'United Kingdom',
    year: 2023,
    class: 'S',
    engine: '4.0L Twin-Turbo V8',
    horsepower: 720,
    torque: 770,
    weight: 1283,
    driveType: 'RWD',
    transmission: '7-Speed SSG',
    topSpeed: 341,
    acceleration: 2.8,
    handling: 9.4,
    braking: 9.1,
    turbo: true,
    stars: 5,
    color: { primary: '#FF6600', accent: '#000000', metalness: 0.85, roughness: 0.12 },
    bodyStyle: 'supercar',
    description: 'Carbon-fiber wrapped missile. Lighter, faster, and more extreme than anything on the road.',
  },
  {
    id: 'bmw_m4',
    name: 'BMW M4 Competition',
    manufacturer: 'BMW',
    country: 'Germany',
    year: 2024,
    class: 'B',
    engine: '3.0L Twin-Turbo Inline-6',
    horsepower: 503,
    torque: 650,
    weight: 1725,
    driveType: 'RWD',
    transmission: '8-Speed Auto',
    topSpeed: 290,
    acceleration: 3.9,
    handling: 8.5,
    braking: 8.2,
    turbo: true,
    stars: 4,
    color: { primary: '#1E40AF', accent: '#c0c0c0', metalness: 0.8, roughness: 0.18 },
    bodyStyle: 'coupe',
    description: 'German muscle. A twin-turbo inline-6 that rewrites the rules of daily driving.',
  },
];

export const getCarById = (id) => CARS.find(car => car.id === id);
export const getCarsByClass = (cls) => CARS.filter(car => car.class === cls);
