export const INTENTS = {
  ABOUT: 'ABOUT',
  PROJECTS: 'PROJECTS',
  SKILLS: 'SKILLS',
  RESUME: 'RESUME',
  ACHIEVEMENTS: 'ACHIEVEMENTS',
  CONTACT: 'CONTACT',
  TIMELINE: 'TIMELINE',
  EDUCATION: 'EDUCATION',
  EXPERIENCE: 'EXPERIENCE',
  OPEN_APP: 'OPEN_APP',
  SEARCH: 'SEARCH',
  HELP: 'HELP',
  UNKNOWN: 'UNKNOWN',
  
  // VS-30.5 Expert Mode Intents
  PORTFOLIO_OS: 'PORTFOLIO_OS',
  RECRUITER_Q_STRENGTHS: 'RECRUITER_Q_STRENGTHS',
  RECRUITER_Q_WEAKNESSES: 'RECRUITER_Q_WEAKNESSES',
  RECRUITER_Q_HIRE: 'RECRUITER_Q_HIRE',
  RECRUITER_Q_GOALS: 'RECRUITER_Q_GOALS',
  RECRUITER_Q_CHALLENGE: 'RECRUITER_Q_CHALLENGE',
  SPECIFIC_PROJECT_TECH: 'SPECIFIC_PROJECT_TECH',
  SKILL_RECOMMENDATION: 'SKILL_RECOMMENDATION'
};
