export const INTENTS = {
  ABOUT: 'ABOUT',
  PROJECTS: 'PROJECTS',
  SKILLS: 'SKILLS',
  RESUME: 'RESUME',
  ACHIEVEMENTS: 'ACHIEVEMENTS',
  CONTACT: 'CONTACT',
  TIMELINE: 'TIMELINE',
  EDUCATION: 'EDUCATION',
  EXPERIENCE: 'EXPERIENCE',
  OPEN_APP: 'OPEN_APP',
  SEARCH: 'SEARCH',
  HELP: 'HELP',
  UNKNOWN: 'UNKNOWN'
};
