import React, { useState } from 'react';
import { usePlacementStore } from '../../../store/usePlacementStore';

export default function InterviewSimulator() {
  const store = usePlacementStore();
  const [inProgress, setInProgress] = useState(false);

  const handleStart = () => setInProgress(true);

  return (
    <div className="placement-card" style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
      <h2 style={{ marginTop: 0 }}>Mock Interview Simulator</h2>
      <p style={{ color: 'var(--color-text-secondary)' }}>
        Simulate real technical and HR interviews dynamically generated by Gemini AI.
      </p>

      {!inProgress ? (
          <div style={{ marginTop: '20px', textAlign: 'center', background: 'rgba(0,0,0,0.2)', padding: '40px 20px', borderRadius: '12px', border: '1px solid var(--color-border)' }}>
              <h3 style={{ margin: '0 0 20px 0', color: 'var(--color-accent)' }}>Ready to test yourself?</h3>
              <p style={{ color: 'var(--color-text-secondary)', marginBottom: '30px' }}>
                  The AI will ask you a mix of DSA, Core CS, and HR questions based on your target company type ({store.companyType}).
              </p>
              <button className="placement-btn-primary" onClick={handleStart} style={{ padding: '15px 40px', fontSize: '1.1rem' }}>
                  Start Mock Interview
              </button>
          </div>
      ) : (
          <div style={{ marginTop: '20px', background: 'rgba(0,0,0,0.2)', padding: '20px', borderRadius: '12px', border: '1px solid var(--color-border)', flex: 1, display: 'flex', flexDirection: 'column' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid var(--color-border)', paddingBottom: '15px', marginBottom: '15px' }}>
                  <span style={{ fontWeight: 600, color: 'var(--color-accent)' }}>Question 1 of 5</span>
                  <span style={{ color: 'var(--color-text-secondary)' }}>Difficulty: Medium</span>
              </div>
              <div style={{ fontSize: '1.2rem', marginBottom: '20px', lineHeight: 1.5 }}>
                  "Can you explain the difference between a process and a thread, and in what scenario you would prefer multi-threading over multi-processing?"
              </div>
              <textarea 
                  placeholder="Type your answer here..."
                  style={{ flex: 1, background: 'rgba(0,0,0,0.3)', border: '1px solid var(--color-border)', borderRadius: '8px', padding: '15px', color: 'white', resize: 'none', fontFamily: 'inherit' }}
              />
              <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '20px' }}>
                  <button className="placement-btn-primary" onClick={() => setInProgress(false)}>Submit Answer</button>
              </div>
          </div>
      )}
    </div>
  );
}
