export const INTENTS = {
  PROJECTS: "PROJECTS",
  ABOUT: "ABOUT",
  SKILLS: "SKILLS",
  ACHIEVEMENTS: "ACHIEVEMENTS",
  RESUME: "RESUME",
  CONTACT: "CONTACT",
  EXPERIENCE: "EXPERIENCE",
  EDUCATION: "EDUCATION",

  // System actions
  OPEN_APP: "OPEN_APP",
  LOCK_SCREEN: "LOCK_SCREEN",
  SHUTDOWN: "SHUTDOWN",
  RESTART: "RESTART",
  PLAY_MUSIC: "PLAY_MUSIC",
  WEATHER_QUERY: "WEATHER_QUERY",

  // Multi-step workflows
  PREPARE_RECRUITER: "PREPARE_RECRUITER",
  SHOW_STRONGEST_WORK: "SHOW_STRONGEST_WORK",

  // Recruiter Questions
  RECRUITER_Q_STRENGTHS: "RECRUITER_Q_STRENGTHS",
  RECRUITER_Q_WEAKNESSES: "RECRUITER_Q_WEAKNESSES",
  RECRUITER_Q_HIRE: "RECRUITER_Q_HIRE",
  RECRUITER_Q_GOALS: "RECRUITER_Q_GOALS",
  RECRUITER_Q_CHALLENGE: "RECRUITER_Q_CHALLENGE",

  // Expert Mode
  EXPERT_COMPARE: "EXPERT_COMPARE",

  // Fallbacks
  SEARCH: "SEARCH",
  UNKNOWN: "UNKNOWN"
};
