import { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ArrowDownloadRegular, DismissRegular } from '@fluentui/react-icons';

const FORMATS = [
  { id: 'json', label: 'JSON', icon: '📦', description: 'Download architecture knowledge base' },
  { id: 'markdown', label: 'Markdown', icon: '📝', description: 'Formatted architecture report' },
  { id: 'png', label: 'PNG', icon: '🖼', description: 'Screenshot of current view' }
];

async function exportJSON() {
  // Dynamically import all JSON files
  const modules = import.meta.glob('../../../ai/knowledge/architecture/*.json', { eager: true });
  const data = {};
  for (const [path, mod] of Object.entries(modules)) {
    const name = path.split('/').pop().replace('.json', '');
    data[name] = mod.default || mod;
  }

  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  downloadBlob(blob, 'portfolio-os-architecture.json');
}

function exportMarkdown() {
  const lines = [
    '# Portfolio OS 2026 — Architecture Report',
    '',
    `Generated: ${new Date().toLocaleString()}`,
    '',
    '---',
    '',
    '## Overview',
    'Portfolio OS is a full-scale operating system simulation built entirely in React.',
    'It features 35+ windowed applications, 30 Zustand stores, a local AI brain, and real backend integrations.',
    '',
    '## Architecture Layers',
    '1. Presentation Layer — React + Framer Motion desktop and mobile UIs',
    '2. Application Layer — 35+ windowed apps (Browser, VS Code, Terminal, etc.)',
    '3. OS Core Layer — Window lifecycle, shortcuts, focus management',
    '4. AI Brain Layer — Local NLP with intent classification and entity extraction',
    '5. State Layer — 30 independent Zustand stores',
    '6. Backend Layer — Express.js + MongoDB APIs',
    '7. Infrastructure Layer — Vite, Vercel, PWA, Service Workers',
    '',
    '## Key Metrics',
    '- 35+ Applications',
    '- 30 Zustand Stores',
    '- 300+ Source Files',
    '- Local AI Brain (no external LLM)',
    '- Real-time Analytics',
    '',
    '---',
    '',
    '*Generated by Architecture Explorer 2.1*'
  ];

  const blob = new Blob([lines.join('\n')], { type: 'text/markdown' });
  downloadBlob(blob, 'portfolio-os-architecture.md');
}

async function exportPNG() {
  try {
    const { default: html2canvas } = await import('html2canvas');
    const target = document.querySelector('[data-arch-content]');
    if (!target) {
      alert('Could not find the content area to capture.');
      return;
    }
    const canvas = await html2canvas(target, { backgroundColor: '#0a0a0a', scale: 2 });
    canvas.toBlob(blob => {
      if (blob) downloadBlob(blob, 'architecture-view.png');
    });
  } catch (err) {
    console.error('PNG export failed:', err);
    alert('PNG export requires html2canvas. Make sure it is installed.');
  }
}

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export default function ExportPanel() {
  const [isOpen, setIsOpen] = useState(false);
  const [exporting, setExporting] = useState(null);

  const handleExport = async (format) => {
    setExporting(format);
    try {
      if (format === 'json') await exportJSON();
      if (format === 'markdown') exportMarkdown();
      if (format === 'png') await exportPNG();
    } catch (err) {
      console.error('Export failed:', err);
    }
    setTimeout(() => setExporting(null), 1000);
  };

  return (
    <div style={{ position: 'relative' }}>
      <button
        onClick={() => setIsOpen(!isOpen)}
        style={{
          display: 'flex', alignItems: 'center', gap: '4px',
          background: 'none', border: 'none', color: '#888',
          cursor: 'pointer', fontSize: '11px', padding: '4px 8px'
        }}
      >
        <ArrowDownloadRegular fontSize={14} /> Export
      </button>

      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0, y: 4, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 4, scale: 0.95 }}
            style={{
              position: 'absolute', bottom: '100%', right: 0, marginBottom: '8px',
              background: '#111', border: '1px solid #333', borderRadius: '8px',
              width: '240px', overflow: 'hidden',
              boxShadow: '0 8px 24px rgba(0,0,0,0.4)'
            }}
          >
            <div style={{ padding: '8px 12px', borderBottom: '1px solid #222', fontSize: '10px', color: '#666', textTransform: 'uppercase', fontWeight: 600, letterSpacing: '1px' }}>
              Export Architecture
            </div>
            {FORMATS.map(format => (
              <button
                key={format.id}
                onClick={() => handleExport(format.id)}
                disabled={exporting === format.id}
                style={{
                  display: 'flex', alignItems: 'center', gap: '10px', width: '100%',
                  padding: '10px 12px', border: 'none', textAlign: 'left',
                  background: exporting === format.id ? 'rgba(76, 175, 80, 0.1)' : 'transparent',
                  color: '#ccc', cursor: 'pointer', fontSize: '12px'
                }}
                onMouseEnter={e => { if (exporting !== format.id) e.currentTarget.style.background = 'rgba(255,255,255,0.05)'; }}
                onMouseLeave={e => { if (exporting !== format.id) e.currentTarget.style.background = 'transparent'; }}
              >
                <span style={{ fontSize: '16px' }}>{format.icon}</span>
                <div>
                  <div style={{ fontWeight: 600 }}>{format.label}</div>
                  <div style={{ fontSize: '10px', color: '#666' }}>{format.description}</div>
                </div>
                {exporting === format.id && <span style={{ marginLeft: 'auto', color: '#4CAF50', fontSize: '11px' }}>✓</span>}
              </button>
            ))}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
